config/routes.rb
Rails.application.routes.draw do

  root 'users#index', as: :users

  resources :posts do
   resources :comments
  end

  namespace :api do
    resources :videos, only: [:index, :show, :create, :update, :destroy]
  end

  get 'users/new' => 'users#new', as: :new_user
  post '/' => 'users#create'

  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"

  get "users/:id" => "users#show", as: :user
  get 'users/:id/new_post' => 'posts#new', as: :add_post

  get 'users/profile/:id' => 'user#id', as: :user_profile

  get 'sessions/new' => 'sessions#new', as: :new_session
  post 'sessions/new' => 'sessions#create', as: :create_session

  get 'sessions/destroy' => 'sessions#destroy', as: :destroy_session

  get 'targets/' => 'targets#index', as: :target

  get 'targets/new' => 'targets#new', as: :new_target
  post 'targets/new' => 'targets#create'




end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :authorize

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
  end

  def destroy
  end


end

app/views/targets/index.html.erb
<h1> You're successfully logged in! Get ready to contribute some greatness! </h1>


<%= link_to "Submit New Post", new_target_path %>
<%= link_to "Logout", destroy_session_path %>

<ul class="list-group">
  <% @posts.each { |post| %>
    <li class="list-group-item">
      <strong><%= link_to post.title, post_path(post) %></strong>
    </li>
    <% } %>

</ul>

app/views/targets/new.html.erb
<h1> Add a new play! </h1>

<%= form_for @target do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
 <!--    #tags
    #http://guides.rubyonrails.org/form_helpers.html#the-select-and-option-tags
    #section 1.1 -->
  <%= f.submit "Add your post" %>
  <% end %>

  <%= link_to "Stop adding a post", targets_path %>