config/routes.rb
Rails.application.routes.draw do

  root 'users#index', as: :users

  resources :posts do
   resources :comments
  end

  namespace :api do
    resources :videos, only: [:index, :show, :create, :update, :destroy]
  end

  get 'users/new' => 'users#new', as: :new_user
  post '/' => 'users#create'

  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"

  get "users/:id" => "users#show", as: :user
  get 'users/:id/new_post' => 'posts#new', as: :add_post

  get 'users/profile/:id' => 'user#id', as: :user_profile

  get 'sessions/new' => 'sessions#new', as: :new_session
  post 'sessions/new' => 'sessions#create', as: :create_session

  get 'sessions/destroy' => 'sessions#destroy', as: :destroy_session

  get 'targets/' => 'targets#index', as: :target

  get 'targets/new' => 'targets#new', as: :new_target
  post 'targets/new' => 'targets#create'




end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts
  has_many :comments
  acts_as_voter
  acts_as_voteable


  validates :email, presence: true, uniqueness: { case_sensitive: false}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authorize_update, only: [:update]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    if User.new(user_params).save
      flash[:success] = "You have successfully registered."
      redirect_to users_path
    else
      flash[:error] = "You have failed to register."
      redirect_to new_user_path
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

  def authorize_update
    @user = User.find(params[:id])
    redirect_to posts_path if @user.id != current_user
  end
end

app/views/users/edit.html.erb
<h1 id="user-edit-header"> Change your info! </h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <%= f.submit "Change yourself" %>
  <% end %>

  <%= link_to "Stop changing yourself", user_path %>

app/views/users/index.html.erb
<div class="homepage" style="padding-top: 150px; height: 800px; background-image: url(assets/images/showus.jpg); background-size: 100%, no-repeat;" >
  <h1 id="loginheader"> Welcome to the club! </h1>


  <p id="intro">Welcome to the secret society of basketball nerds, joining is as simple as registering an account! </p>

  <div class="button">
    <%= link_to new_user_path do %>
    <id="register" class="btn btn-large btn-warning">Register
    <% end %>
    <% if current_user %>
      <%= link_to destroy_session_path do %>
      <id="logout" class="btn btn-large btn-warning">Logout</id="logout">
      <% end %>

  <% else %>
  <%= render "layouts/register/login_modal" %>
  <%= link_to "Login", "#login", "data-toggle" => "modal", :class => 'btn btn-large btn-warning' %>

    <% end %>
  <% flash.each do |key, value| %>
  <div class="<%= key %>"><%= value %></div>
  <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="registerpage" style="padding-top: 150px; height: 800px; background-image: url(/assets/images/bird-erving.jpg);">
<h1 id="reg-header">Register here!</h1>

<%= form_for @user do |f| %>
  <% flash.each do |key, value| %>
    <div class="<%= key %>" > <%= value %> </div>
  <% end %>
  <div id="name-reg">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'email-font' %>
  </div>
  <div id="email-reg">
  <%= f.label :email %>
  <%= f.email_field :email, class: 'email-font'%>
  <br>
  </div>
  <div id="pw-reg">
  <%= f.label :password %>
  <%= f.password_field :password, class: 'email-font' %>
  <br>
  </div>
  <div id="pwc-reg">
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'email-font' %>
  <br>
  </div>
  <div id="sub-reg">
  <%= f.submit "Register!", :class => "btn btn-success" %>

  </div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="prof-bg" style="background-image: url(/assets/images/flcl.jpg)">
<h1 id="profhead"> Welcome!<%= @user.name %> </h1>

<div class="prof-props">
  <p id="prof-intro">Welcome to your profile, you can check out your posts,
  <br>
   and your comments here.
  <br>
  <br>
  <br>
  <br>
  </p>
    <p id="info-head">
      Info
    </p>
  Name: <%= @user.name %>
  <br>
  Email: <%= @user.email %>

</div>
<br>
<br>
<br>
<br>
<div class="prof-posts">
  <p id="prof-post-intro">
  These are your posts:
  </p>
  <ul class="prof-post-list-group">
    <% @user.posts.each do |post| %>
    <li class="prof-post-list-group-item" %>
      <%= link_to post.title, post_path(post.id) %>
    </li>
    <% end %>
  </ul>
</div>
<div class="prof-comments">
  <p id="prof-comments-intro">
  These are your comments:
  </p>
  <ul class="prof-list-group">
    <% @user.comments.each do |comment| %>
    <li class="prof-list-group-item">
      <%= link_to comment.body, post_path(comment.post.id) %>
    </li>
    <% end %>
  </ul>
</div>
<br>
<br>
<%= link_to posts_path do %>
  <id="return-btn" class="btn btn-lg btn-default"> Return to posts </id="return-btn">
<% end %>
<div class="edit-user-btn">
<% if current_user.id == @user.id %>
  <%= link_to edit_user_path do %>
    <id="edit-user-btn" class="btn btn-lg btn-default">Edit User
  </id="edit-user-btn">
    <% end %>
  <% end %>
  </div>
</div>