config/routes.rb
Rails.application.routes.draw do

  root 'users#index', as: :users

  resources :posts do
   resources :comments
  end

  namespace :api do
    resources :videos, only: [:index, :show, :create, :update, :destroy]
  end

  get 'users/new' => 'users#new', as: :new_user
  post '/' => 'users#create'

  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"

  get "users/:id" => "users#show", as: :user
  get 'users/:id/new_post' => 'posts#new', as: :add_post

  get 'users/profile/:id' => 'user#id', as: :user_profile

  get 'sessions/new' => 'sessions#new', as: :new_session
  post 'sessions/new' => 'sessions#create', as: :create_session

  get 'sessions/destroy' => 'sessions#destroy', as: :destroy_session

  get 'targets/' => 'targets#index', as: :target

  get 'targets/new' => 'targets#new', as: :new_target
  post 'targets/new' => 'targets#create'




end

app/models/post.rb
class Post < ActiveRecord::Base
  include ApplicationHelper

  belongs_to :user
  has_many :comments
  has_many :videos
  validates_presence_of :title, :body, :youtube_url


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate, only: [:create, :destroy]
  before_action :authorize_update, only: [:update]
  before_action :authorize_destroy, only: [:destroy]

  def index
    @posts = Post.all
    @user = current_user
    @posts = Post.order("created_at DESC")
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_path
    else
      render :edit
    end
  end

  def youtube_url
    require 'embed'
  end

  def create
    @post = Post.new(post_params)
    # @post.user_id = session[:user_id]
    if @post.save
      redirect_to posts_path
    else
      flash[:error] = "Your post needs a title/body/youtube url"
      redirect_to new_post_path
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :youtube_url, :user_id)
    end

    def authenticate
      redirect_to new_session_path, alert: 'You must be logged in first.' if current_user.nil?
    end

    def authorize_create
      @user = User.find(params[:user_id])
      redirect_to posts_path if @user != current_user
    end

    def authorize_update
      @post = Post.find(params[:id])
      redirect_to posts_path if @post.user != current_user
    end

    def authorize_destroy
      @post = Post.find(params[:id])
      redirect_to posts_path if @post.user != current_user
    end

end

app/views/posts/comment_modal.html.erb
<div class="modal fade in" id="comments">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">x</button>
    <h2 id="modalsi">Write your comment</h2>
  </div>
  <div class="modal-body">
    <%= form_for :comment, url: create_comment_path do |f| %>
    <form>
      <fieldset class="form-group">
        <%= f.label :body%>
        <br>
        <%= f.text_area :body %>
      </fieldset>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :post_id, :value => @post.id %>
        <br>
        <br>
      <%= f.submit "Add your comment", :class => 'btn btn-med btn-primary', :id => 'addcomment' %>
  <% end %>
  </form>
  </div>
</div>

app/views/posts/edit.html.erb
<h1> Change your post! </h1>

<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :video %>
    <%= f.text_field :youtube_url %> <br>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

 <!--    #tags
    #http://guides.rubyonrails.org/form_helpers.html#the-select-and-option-tags
    #section 1.1 -->
  <%= f.submit "Submit Changes", method: :update %>
  <% end %>

  <%= link_to "Stop adding a post", posts_path %>

app/views/posts/index.html.erb
<div id="postpage" class="col-lg-12" style="background-image: url(/assets/images/light-wood.jpg); background-size: 100%; background-repeat: repeat-y;">
  <div id="flashsuccess">
    <% flash.each do |key, value| %>
    <div class="<%= key %>"><%= value %></div>
    <% end %>
  </div>
  <div class="mng-btns">
    <%= link_to user_path(@user) do %>
      <id="prof-btn" class="btn btn-med btn-success">User Profile
      <% end %>
    <%= link_to add_post_path(@user) do %>
      <id="new-post-btn" class="btn btn-med btn-primary">Add New Post
      <% end %>
    <%= link_to destroy_session_path do %>
      <id="logout-btn" class="btn btn-med btn-danger">Logout
      <% end %>
  </div>
  <div class="allposts col-lg-12">
    <ul class="list-group" style="background-image: url(/assets/images/light-wood.jpg)">
      <% @posts.each { |post| %>
       <li class="list-group-item" id="eachpost" style="background-image: url(/assets/images/light-wood.jpg)">
          <strong><%= link_to post.title, post_path(post.id), :class => "title-font" %></strong>
          <br>

          <br>
          <div class="page-container">
            <%= embed(post.youtube_url) %>
          </div>
       </li>
      <% } %>
    </ul>
  </div>
</div>

app/views/posts/new.html.erb
<div class="newpostbg" style="padding-top: 15px; height: 800px; background-image: url(/assets/images/lbj-wade.jpg">
<h1 id="newposthead"> Add a new play! </h1>

<div class="post-form">
<%= form_for @post do |f| %>
  <div id="post-tit">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :video %>
    <%= f.text_field :youtube_url %> <br>
  </div>
  <div id="post-body">
    <%= f.label :body %>
    <%= f.text_area :body %>

    <%= f.hidden_field :user_id, :value => @user.id%>
  </div>
</div>
 <!--    #tags
    #http://guides.rubyonrails.org/form_helpers.html#the-select-and-option-tags
    #section 1.1 -->
  <div class="sub-btn">
  <%= f.submit do %>
  <id="postsubmit" class="btn btn-med btn-success">Add your post</id="postsubmit">
  <% end %>
  <% end %>

  <%= link_to posts_path do %>
    <id="returnpost" class="btn btn-med btn-danger">Stop adding posts</id="returnpost">
  <% end %>
  </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post-bg" style="padding-top :15px; padding-bottom: 20px; background-image: url(/assets/images/sriracha.png">
<h1 id="post-title"> <%= @post.title %> </h1>
<div class="return-btn">
<%= link_to posts_path do %>
  <id="return-btn" class="btn btn-med btn-primary">Return to all posts</id="return-btn">
  <% end %>
</div>
<br>
<% if current_user == @post.user %>
<div class="show-btns">
<%= link_to edit_post_path(@post.id) do %>
  <id="edit-post" class="btn btn-med btn-info">Edit your post!</id="edit-post">
  <% end %>
<%= link_to post_path(@post.id), method: :delete do %>
  <id="dlt-post" class="btn btn-med btn-danger">Delete your post</id="dlt-post">
  <% end %>

<% end %>
<br>
<br>
<div class="post-body">
<%= @post.body %>
</div>
<div class="post-container">
  <%= embed(@post.youtube_url) %>
</div>

<div class="cmt-mod">
  <%= render "posts/modal/comment_modal" %>
  <%= link_to "Add a comment!", "#comments", "data-toggle" => "modal",:id=>"cmt-mod", :class=> 'btn btn-large btn-primary' %>
</div>
<br>
<br>

<div class="comments-list"
<ul class="list-group">
  <%  @post.comments.each do |comment|%>
    <li class="list-group-item">
    <%= comment.body %>
    </li>
<% end %>
</ul>
</div>




</div>