config/routes.rb
Rails.application.routes.draw do

  root 'users#index', as: :users

  resources :posts do
   resources :comments
  end

  namespace :api do
    resources :videos, only: [:index, :show, :create, :update, :destroy]
  end

  get 'users/new' => 'users#new', as: :new_user
  post '/' => 'users#create'

  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"

  get "users/:id" => "users#show", as: :user
  get 'users/:id/new_post' => 'posts#new', as: :add_post

  get 'users/profile/:id' => 'user#id', as: :user_profile

  get 'sessions/new' => 'sessions#new', as: :new_session
  post 'sessions/new' => 'sessions#create', as: :create_session

  get 'sessions/destroy' => 'sessions#destroy', as: :destroy_session

  get 'targets/' => 'targets#index', as: :target

  get 'targets/new' => 'targets#new', as: :new_target
  post 'targets/new' => 'targets#create'




end

app/models/post.rb
class Post < ActiveRecord::Base
  include ApplicationHelper

  belongs_to :user
  has_many :comments
  has_many :videos
  validates_presence_of :title, :body, :youtube_url


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate, only: [:create, :destroy]
  before_action :authorize_update, only: [:update]
  before_action :authorize_destroy, only: [:destroy]

  def index
    @posts = Post.all
    @user = current_user
    @posts = Post.order("created_at DESC")
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_path
    else
      render :edit
    end
  end

  def youtube_url
    require 'embed'
  end

  def create
    @post = Post.new(post_params)
    # @post.user_id = session[:user_id]
    if @post.save
      redirect_to posts_path
    else
      flash[:error] = "Your post needs a title/body/youtube url"
      redirect_to new_post_path
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :youtube_url, :user_id)
    end

    def authenticate
      redirect_to new_session_path, alert: 'You must be logged in first.' if current_user.nil?
    end

    def authorize_create
      @user = User.find(params[:user_id])
      redirect_to posts_path if @user != current_user
    end

    def authorize_update
      @post = Post.find(params[:id])
      redirect_to posts_path if @post.user != current_user
    end

    def authorize_destroy
      @post = Post.find(params[:id])
      redirect_to posts_path if @post.user != current_user
    end

end

app/views/posts/modal/_comment_modal.html.erb
<div class="modal fade in" id="comments">
  <div class="commodal-header">
    <button class="close" data-dismiss="modal">x</button>
    <h2 id="modalcom">Write your comment</h2>
  </div>
  <div class="commodal-body">
    <%= form_for :comment, url: post_comments_path(@post) do |f| %>
      <form>
      <fieldset class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body %>
      </fieldset>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :post_id, :value => @post.id %>
        <br>
        <br>
      </div>
      <%= f.submit "Add your comment", :class => 'btn btn-med btn-primary', :id => 'addcomment' %>
  <% end %>
  </div>
</div>